services:
    sherlockode_configuration.field.text:
        class: Sherlockode\ConfigurationBundle\FieldType\TextField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.textarea:
        class: Sherlockode\ConfigurationBundle\FieldType\TextareaField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.url:
        class: Sherlockode\ConfigurationBundle\FieldType\UrlField
        tags:
            - {name: sherlockode_configuration.field }
    sherlockode_configuration.field.datetime:
        class: Sherlockode\ConfigurationBundle\FieldType\DateTimeField
        tags:
            - {name: sherlockode_configuration.field }
